# Generated by Django 4.2.4 on 2023-11-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_status", models.CharField(max_length=255, verbose_name="訂單問題")),
                (
                    "shipping_delivery",
                    models.CharField(max_length=255, verbose_name="運送問題"),
                ),
                ("payment", models.CharField(max_length=255, verbose_name="付款方式")),
                (
                    "return_exchange",
                    models.CharField(max_length=255, verbose_name="退款與換貨"),
                ),
                (
                    "privacy_policy",
                    models.CharField(max_length=255, verbose_name="隱私權政策"),
                ),
            ],
            options={
                "verbose_name": "常見問題",
                "verbose_name_plural": "常見問題",
                "db_table": "faq",
            },
        ),
    ]
