# Generated by Django 4.2.4 on 2023-11-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faqmodels",
            name="order_status",
            field=models.TextField(blank=True, verbose_name="訂單問題"),
        ),
        migrations.AlterField(
            model_name="faqmodels",
            name="payment",
            field=models.TextField(blank=True, verbose_name="付款方式"),
        ),
        migrations.AlterField(
            model_name="faqmodels",
            name="privacy_policy",
            field=models.TextField(blank=True, verbose_name="隱私權政策"),
        ),
        migrations.AlterField(
            model_name="faqmodels",
            name="return_exchange",
            field=models.TextField(blank=True, verbose_name="退款與換貨"),
        ),
        migrations.AlterField(
            model_name="faqmodels",
            name="shipping_delivery",
            field=models.TextField(blank=True, verbose_name="運送問題"),
        ),
    ]
