# Generated by Django 4.2.4 on 2023-11-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="顧客名稱")),
                ("email", models.EmailField(max_length=255, verbose_name="電子信箱")),
                (
                    "subject",
                    models.CharField(max_length=255, null=True, verbose_name="主旨"),
                ),
                ("message", models.TextField(blank=True, verbose_name="內容")),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立日期"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新日期"),
                ),
            ],
            options={
                "verbose_name_plural": "聯絡我們列表",
                "db_table": "contact",
            },
        ),
    ]
