# Generated by Django 4.2.4 on 2023-11-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmodels",
            options={"verbose_name": "聯絡我們", "verbose_name_plural": "聯絡我們"},
        ),
    ]
