# Generated by Django 4.2.4 on 2023-11-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="memberModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="用戶名稱")),
                ("email", models.EmailField(max_length=200, verbose_name="電子信箱")),
                ("password", models.CharField(max_length=200, verbose_name="密碼")),
                ("birthday", models.DateField(verbose_name="生日")),
                ("mobile", models.CharField(max_length=20, verbose_name="行動電話")),
                ("address", models.CharField(max_length=200, verbose_name="地址")),
                ("c_date", models.DateField(auto_now=True, verbose_name="創立日期")),
            ],
            options={
                "verbose_name_plural": "會員列表",
                "db_table": "member",
            },
        ),
    ]
