# Generated by Django 4.2.4 on 2023-11-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_category",
                    models.CharField(max_length=10, verbose_name="文章類別"),
                ),
            ],
            options={
                "verbose_name_plural": "文章類別",
                "db_table": "article_category",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="標題")),
                ("content", models.TextField(blank=True, verbose_name="文章內容")),
                ("author_name", models.CharField(max_length=50, verbose_name="作者")),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="修改日期"),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="建立日期"),
                ),
                (
                    "article_photo",
                    models.ImageField(
                        max_length=200, upload_to="article_photo", verbose_name="文章圖片"
                    ),
                ),
                (
                    "article_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.articlecategory",
                        verbose_name="文章類別",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "文章",
                "db_table": "article",
            },
        ),
    ]
