# Generated by Django 4.2.4 on 2023-11-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="small_content",
            field=models.TextField(blank=True, verbose_name="文章大綱"),
        ),
    ]
