# Generated by Django 4.2.4 on 2023-11-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_small_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "文章", "verbose_name_plural": "文章"},
        ),
        migrations.AlterModelOptions(
            name="articlecategory",
            options={"verbose_name": "文章類別", "verbose_name_plural": "文章類別"},
        ),
    ]
