# Generated by Django 4.2.4 on 2023-11-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "產品列表"},
        ),
        migrations.AlterModelOptions(
            name="productphoto",
            options={"verbose_name_plural": "產品圖片列表"},
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(verbose_name="特價"),
        ),
    ]
