# Generated by Django 4.2.4 on 2023-11-05 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
