# Generated by Django 4.2.4 on 2023-11-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_remove_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_photo",
            field=models.ImageField(
                max_length=200,
                null=True,
                upload_to="category_photo",
                verbose_name="類別圖片",
            ),
        ),
    ]
