# Generated by Django 4.2.4 on 2023-11-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_product_product_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_photo",
            new_name="image",
        ),
    ]
