# Generated by Django 4.2.4 on 2023-11-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_rename_product_photo_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "類別列表", "verbose_name_plural": "類別列表"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "產品列表", "verbose_name_plural": "產品列表"},
        ),
        migrations.AlterModelOptions(
            name="productphoto",
            options={"verbose_name": "產品圖片列表", "verbose_name_plural": "產品圖片列表"},
        ),
    ]
