# Generated by Django 4.2.4 on 2023-11-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BannerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        max_length=255, upload_to="banner", verbose_name="首頁banner圖"
                    ),
                ),
                ("c_date", models.DateField(auto_now=True, verbose_name="創立日期")),
            ],
            options={
                "verbose_name_plural": "首頁Banner列表",
                "db_table": "banner",
            },
        ),
    ]
