# Generated by Django 4.2.4 on 2023-11-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bannermodel",
            options={"verbose_name": "首頁Banner", "verbose_name_plural": "首頁Banner"},
        ),
    ]
