# Generated by Django 4.2.4 on 2023-11-17 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=20, null=True, verbose_name="全名"),
                ),
                (
                    "email",
                    models.CharField(max_length=50, null=True, verbose_name="訂購者信箱"),
                ),
                (
                    "phone",
                    models.CharField(max_length=15, null=True, verbose_name="電話"),
                ),
                ("city", models.CharField(max_length=10, null=True, verbose_name="城市")),
                (
                    "address",
                    models.CharField(max_length=20, null=True, verbose_name="住址"),
                ),
                (
                    "zip_code",
                    models.CharField(max_length=10, null=True, verbose_name="區碼"),
                ),
                (
                    "bank_account",
                    models.CharField(max_length=10, null=True, verbose_name="銀行帳號"),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="付款狀態")),
                (
                    "pay_type",
                    models.CharField(max_length=10, null=True, verbose_name="付款方式"),
                ),
                (
                    "subtotal",
                    models.IntegerField(default=0, null=True, verbose_name="價格"),
                ),
                (
                    "shipping",
                    models.IntegerField(default=0, null=True, verbose_name="運費"),
                ),
                (
                    "in_total",
                    models.IntegerField(default=0, null=True, verbose_name="總價"),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立日期"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新日期"),
                ),
            ],
            options={
                "verbose_name": "訂單管理",
                "verbose_name_plural": "訂單管理",
                "db_table": "order_category",
                "ordering": ("-create_date",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=100, null=True, verbose_name="產品名稱"),
                ),
                (
                    "unitprice",
                    models.IntegerField(default=0, null=True, verbose_name="單位"),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, null=True, verbose_name="數量"),
                ),
                (
                    "dtotal",
                    models.IntegerField(default=0, null=True, verbose_name="總共"),
                ),
                (
                    "dorder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.order",
                        verbose_name="訂單編號",
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單明細",
                "verbose_name_plural": "訂單明細",
                "db_table": "orderitem_detail",
            },
        ),
    ]
